services:
  backend:
    build:
      context: ../backend
    image: repertuar/backend-app:latest
    ports:
      - "4000:4000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AUTH_SECRET=${AUTH_SECRET}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0 # или mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306" # Пробрасываем порт для доступа с хоста (опционально)
    volumes:
      - mysql_data:/var/lib/mysql # Сохраняем данные между перезапусками
    command: >
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 5s
      timeout: 60s
      retries: 5

  frontend:
    build:
      context: ../frontend
    image: repertuar/frontend-app:latest
    ports:
      - "5173:5173"
      - "3000:3000"
    environment:
      - NUXT_VITE_HMR_PORT=5173
      - NUXT_PUBLIC_API_BASE=http://localhost:4000/api/v1/
      - BASE_URL=http://localhost:4000/api/v1/
      - APP_URL=http://localhost:4000/api/v1/
      - AUTH_ORIGIN=http://localhost:4000/api/v1/
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
    # volumes:
    #   - ../frontend:/app
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Проброс порта 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Монтируем конфигурацию Nginx
    depends_on:
      - frontend
      - backend
volumes:
  mysql_data:
