services:
  backend:
    build:
      context: ./abonements-backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "4000:4000"
    command: npm run dev # Запуск в production-режиме (нужно изменить на start!!!!!!!!!!!)
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./swimming-pool-crm
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    command: npm run build && npm run start # Сборка и запуск
    environment:
      - NODE_ENV=production

  mysql:
    ports: [] # Убираем проброс портов для безопасности
